# Generated by Django 5.0.6 on 2024-07-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depositaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=50)),
                ('sous_prefecture', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=50)),
                ('secteur', models.CharField(max_length=50)),
                ('emails', models.CharField(max_length=50)),
                ('telephones', models.CharField(max_length=50)),
                ('cellulaires', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
                ('reseaux_sociaux', models.CharField(max_length=50)),
                ('est_personne', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
                ('date_modif', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('abrege', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeCommercial',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('abrege', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('abrege', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('abrege', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField()),
                ('superficie_habitable', models.FloatField()),
                ('visible', models.BooleanField()),
                ('statut', models.CharField(max_length=50)),
                ('sous_prefecture', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=50)),
                ('secteur', models.CharField(max_length=50)),
                ('type_terrain', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_principal', models.CharField(max_length=50)),
                ('plan_principal', models.CharField(max_length=50)),
                ('video_visite', models.CharField(max_length=50)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('date_modif', models.DateField(auto_now=True)),
                ('cout_dossier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apport_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bientype')),
                ('depositaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.depositaires')),
            ],
        ),
        migrations.CreateModel(
            name='BienDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bien')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.doc')),
            ],
            options={
                'unique_together': {('bien', 'doc')},
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='docs',
            field=models.ManyToManyField(through='bien_immobiliers.BienDoc', to='bien_immobiliers.doc'),
        ),
        migrations.CreateModel(
            name='BienMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bien')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.mediatype')),
            ],
            options={
                'unique_together': {('bien', 'media_type')},
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='medias',
            field=models.ManyToManyField(through='bien_immobiliers.BienMedia', to='bien_immobiliers.mediatype'),
        ),
        migrations.AddField(
            model_name='bien',
            name='mode_commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.modecommercial'),
        ),
        migrations.CreateModel(
            name='BienPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bien')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.piece')),
            ],
            options={
                'unique_together': {('bien', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='pieces',
            field=models.ManyToManyField(through='bien_immobiliers.BienPiece', to='bien_immobiliers.piece'),
        ),
        migrations.AddField(
            model_name='bien',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.standing'),
        ),
    ]
