# Generated by Django 5.0.6 on 2024-07-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaison',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='type_maison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bien_immobiliers.typemaison'),
        ),
    ]
