# Generated by Django 5.0.6 on 2024-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0002_typemaison_bien_type_maison'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='nb_piece',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
