# Generated by Django 5.0.6 on 2024-07-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0003_bien_nb_piece'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depositaires',
            new_name='Depositaire',
        ),
    ]
