# Generated by Django 5.0.6 on 2024-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0004_rename_depositaires_depositaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='image_principal',
            field=models.ImageField(upload_to='biens/photos'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='plan_principal',
            field=models.ImageField(upload_to='biens/plans'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='video_visite',
            field=models.ImageField(upload_to='biens/videos'),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='logo',
            field=models.ImageField(upload_to='depositaires/logos'),
        ),
    ]
