# Generated by Django 5.0.6 on 2024-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0005_alter_bien_image_principal_alter_bien_plan_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='gps',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
