# Generated by Django 5.0.6 on 2024-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0006_bien_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContact',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bien',
            name='type_terrain',
        ),
        migrations.RemoveField(
            model_name='depositaire',
            name='cellulaires',
        ),
        migrations.RemoveField(
            model_name='depositaire',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='depositaire',
            name='est_personne',
        ),
        migrations.RemoveField(
            model_name='depositaire',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='depositaire',
            name='telephones',
        ),
        migrations.AddField(
            model_name='depositaire',
            name='gps',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depositaire',
            name='personne_morale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositaire',
            name='contacts',
            field=models.ManyToManyField(to='bien_immobiliers.typecontact'),
        ),
    ]
