# Generated by Django 5.0.6 on 2024-07-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0007_typecontact_remove_bien_type_terrain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositaireContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.depositaire')),
                ('type_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.typecontact')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='depositaire',
        #     name='contacts',
        #     field=models.ManyToManyField(through='bien_immobiliers.DepositaireContact', to='bien_immobiliers.typecontact'),
        # ),
        migrations.RemoveField(
            model_name='depositaire',
            name='contacts',
        ),
        migrations.AddField(
            model_name='depositaire',
            name='contacts',
            field=models.ManyToManyField(related_name='depositaires', through='bien_immobiliers.DepositaireContact', to='bien_immobiliers.typecontact'),
        ),
    ]
