# Generated by Django 5.0.6 on 2024-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0008_depositairecontact_alter_depositaire_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositairecontact',
            name='valeur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='contacts',
            field=models.ManyToManyField(through='bien_immobiliers.DepositaireContact', to='bien_immobiliers.typecontact'),
        ),
    ]
