# Generated by Django 5.0.6 on 2024-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0010_alter_bienmedia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaire',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
