# Generated by Django 5.0.6 on 2024-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0011_alter_depositaire_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaire',
            name='commune',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='logo',
            field=models.ImageField(null=True, upload_to='depositaires/logos'),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='slogan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='sous_prefecture',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
