# Generated by Django 5.0.6 on 2024-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0012_alter_depositaire_commune_alter_depositaire_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaire',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='date_modif',
            field=models.DateField(auto_now=True),
        ),
    ]
