# Generated by Django 5.0.6 on 2024-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0013_alter_depositaire_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
