# Generated by Django 5.0.6 on 2024-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0014_alter_depositaire_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositaire',
            name='reseaux_sociaux',
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='gps',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='depositaires/logos'),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaire',
            name='sous_prefecture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
