# Generated by Django 5.0.6 on 2024-07-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0015_remove_depositaire_reseaux_sociaux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaire',
            name='secteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
