# Generated by Django 5.0.6 on 2024-07-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0016_alter_depositaire_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalisationType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bien',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='sous_prefecture',
        ),
        migrations.AddField(
            model_name='depositaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BienLocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=100)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bien')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.localisationtype')),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='localisation',
            field=models.ManyToManyField(through='bien_immobiliers.BienLocalisation', to='bien_immobiliers.localisationtype'),
        ),
    ]
