# Generated by Django 5.0.6 on 2024-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0018_statut_alter_bien_nb_piece_alter_bien_standing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisationtype',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statut',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
