# Generated by Django 5.0.6 on 2024-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0019_alter_localisationtype_ordre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='image_principal',
            field=models.ImageField(blank=True, null=True, upload_to='biens/photos'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='plan_principal',
            field=models.ImageField(blank=True, null=True, upload_to='biens/plans'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='video_visite',
            field=models.ImageField(blank=True, null=True, upload_to='biens/videos'),
        ),
        migrations.AlterField(
            model_name='bienpiece',
            name='nombre',
            field=models.IntegerField(),
        ),
    ]
