# Generated by Django 5.0.6 on 2024-07-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0020_alter_bien_image_principal_alter_bien_plan_principal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='pro_im',
            new_name='promotion_immobiliere',
        ),
        migrations.AlterField(
            model_name='bien',
            name='apport_initial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='cout_dossier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='mode_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bien_immobiliers.modecommercial'),
        ),
    ]
