# Generated by Django 5.0.6 on 2024-07-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0021_rename_pro_im_bien_promotion_immobiliere_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biendoc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bienmedia',
            unique_together=set(),
        ),
    ]
