# Generated by Django 5.0.6 on 2024-07-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0022_alter_biendoc_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bienpiece',
            unique_together=set(),
        ),
    ]
