# Generated by Django 5.0.6 on 2024-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0023_alter_bienpiece_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='localisation',
        ),
        migrations.AddField(
            model_name='bien',
            name='nb_appartements',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='nb_etage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bienmedia',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
