# Generated by Django 5.0.6 on 2024-07-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0024_remove_bien_localisation_bien_nb_appartements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienmedia',
            name='detail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
