# Generated by Django 5.0.6 on 2024-07-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0025_bienmedia_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bienpiece',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bienpiece',
            name='interieur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bienpiece',
            name='superficie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bienpiece',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.niveau'),
        ),
    ]
