# Generated by Django 5.0.6 on 2024-07-31 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0026_niveau_bien_description_bienpiece_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienmedia',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.niveau'),
        ),
    ]
