# Generated by Django 5.0.6 on 2024-08-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0027_bienmedia_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='depositaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='bien_immobiliers.depositaire'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='mode_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='bien_immobiliers.modecommercial'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='standing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='bien_immobiliers.standing'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='bien_immobiliers.statut'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='bien_immobiliers.bientype'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_maison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='bien_immobiliers.typemaison'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='utilisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='bien_immobiliers.utilisation'),
        ),
    ]
