# Generated by Django 5.0.2 on 2024-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0028_alter_bien_depositaire_alter_bien_mode_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='annee_construction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
