# Generated by Django 5.0.2 on 2024-08-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0029_bien_annee_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='depositaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
