# Generated by Django 5.0.2 on 2024-08-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0031_bien_commodités'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='commodités',
            new_name='commodites',
        ),
    ]
