# Generated by Django 5.0.6 on 2024-08-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0032_rename_commodités_bien_commodites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localisationtype',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='bienmedia',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
