# Generated by Django 5.0.6 on 2024-08-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0033_alter_localisationtype_options_bienmedia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='localisations',
            field=models.ManyToManyField(through='bien_immobiliers.BienLocalisation', to='bien_immobiliers.localisationtype'),
        ),
        migrations.CreateModel(
            name='BienNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ImageField(upload_to='medias')),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bien')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='niveau',
            field=models.ManyToManyField(through='bien_immobiliers.BienNiveau', to='bien_immobiliers.niveau'),
        ),
        migrations.AlterField(
            model_name='bienmedia',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bienniveau'),
        ),
        migrations.AlterField(
            model_name='bienpiece',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bienniveau'),
        ),
    ]
