# Generated by Django 5.0.6 on 2024-08-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0034_bien_localisations_bienniveau_bien_niveau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienniveau',
            name='plan',
        ),
    ]
