# Generated by Django 5.0.6 on 2024-08-06 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0035_remove_bienniveau_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienpiece',
            name='nombre',
        ),
        migrations.AddField(
            model_name='bienmedia',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bien_immobiliers.bienpiece'),
        ),
    ]
