# Generated by Django 5.0.6 on 2024-08-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0037_rename_interieur_bienpiece_commodites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienpiece',
            old_name='commodites',
            new_name='commodite',
        ),
    ]
