# Generated by Django 5.0.2 on 2024-08-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0038_rename_commodites_bienpiece_commodite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienmedia',
            name='detail',
        ),
    ]
