# Generated by Django 5.0.2 on 2024-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0039_remove_bienmedia_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienmedia',
            name='page',
            field=models.CharField(choices=[('listpage', 'ListPage'), ('detailpage', 'DetailPage')], default='ListPage', max_length=10),
        ),
    ]
