# Generated by Django 5.0.2 on 2024-08-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0040_bienmedia_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienmedia',
            name='page',
        ),
    ]
