# Generated by Django 5.0.6 on 2024-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0041_remove_bienmedia_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('temoignages', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='biens/plans')),
            ],
        ),
    ]
