# Generated by Django 5.0.6 on 2024-08-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0042_temoignages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temoignages',
            new_name='Temoignage',
        ),
    ]
