# Generated by Django 5.0.2 on 2024-08-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0043_rename_temoignages_temoignage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
