# Generated by Django 5.0.2 on 2024-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0044_temoignage_fonction_alter_temoignage_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaire',
            name='branding_images',
            field=models.ImageField(blank=True, null=True, upload_to='depositaires/logos'),
        ),
    ]
