# Generated by Django 5.0.2 on 2024-08-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_immobiliers', '0045_depositaire_branding_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaire',
            name='slogan',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
